# Site settings
title: Deep Learning Study
email: marshallixp@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Explain the state-of-art research and Track our latest experiments.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
# cd twitter_username: jekyllrb
github_username:  marshallixp

# Build settings
markdown: rDiscount
